# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :custom_lane do
    # add actions here: https://docs.fastlane.tools/actions
  end

  desc "Push a new beta build to TestFlight"
  lane :beta do
    # 1. Automatically manage signing (requires App Store Connect credentials to be set up)
    # match(type: "appstore") # Uncomment if you use fastlane match
    
    # 2. Build the app using the gym action
    build_app(
      scheme: "Pilot",
      export_method: "app-store"
    )
    
    # 3. Upload to TestFlight
    upload_to_testflight
  end
end
